version:  '3.7'
 
services:
  database:
    # image: mariadb:10.3
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSORD: pass
      MYSQL_DATABASE: exercice
    volumes:
      - ./services/sql/my.cnf:/etc/mysql/my.cnf
    container_name: t_db
    ports:
      - 3306:3306
    networks: 
      - default

  php:
    build:
      context: services/php
    restart: always
    container_name: t_php
    volumes:
      - './src/:/var/www/html'
    depends_on: 
      - database
    networks: 
      - default

  nginx:
    image: nginx:latest
    restart: always
    container_name: t_ngn
    volumes:
      - './src/:/var/www/html'
      - './services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 80:80
    depends_on:
      - php
    networks: 
      - default

networks: 
  default: