api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    # Allows you to specify a parameter name for each entity (not only one) which will use the OrderFilter::class
    # collection:
    #     order_parameter_name: '_order'
