vich_uploader:
    db_driver: orm

    mappings:
       images:
           uri_prefix: /images
           upload_destination: '%kernel.project_dir%/public/images'

           # Rename uploaded files
           namer: Vich\UploaderBundle\Naming\UniqidNamer

        # profile_pictures:
        # pdf:
        # backgrounds:
        # etc …